#%RAML 1.0
title: My API with structure
mediaType: application/json
baseUri: https://api.domain.com

/endpoint:
  get:
  post:
  put:
  delete:
/resource:
  get:
  /subreource:
    get:
    /sub-sub-resource:
      get:
      post:
      put:
      delete:
